In [3]:
#Load csv fil og lav til panda dataframe
import pandas as pd
df = pd.read_csv("GoMore_Data_DK.csv", sep=',', low_memory=False)
df.head(4)

13653

In [4]:
#Rename datetime column
df = df.rename(columns={'depart_at': 'depart_date_time'})
df.head(3)

,id,depart_date_time,seats,prefs,notes,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,...,comfort,smoking,id_arr,latitude_arr,longitude_arr,name_arr,id_dep,latitude_dep,longitude_dep,name_dep
0,7385002,2018-08-07T15:30:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Opsamling Rødovre station. Bilen er lille. Ikk...,0,269889,12.5,100,NaN,...,0,0,25834238,56.025167,9.896857,Smukfest,25834237,55.673514,12.465726,Rødovre
1,7385006,2018-08-07T14:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,1399528,12.5,100,NaN,...,1,0,25829883,55.676097,12.568337,København,25829881,56.460584,10.036539,Randers
2,7385007,2018-08-09T08:30:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Afgang fra Vesterbro Brandstation. Tidspunkt k...,0,1438456,12.5,100,NaN,...,0,0,25829865,55.844405,9.237394,Give,25829864,55.657333,12.538118,Enghavevej 168

In [5]:
#split datetime into date and time variables
from datetime import datetime as dt

In [6]:
#Creating the variable with the correct timezone
time = []
for i in range(0, len(df),1):
    time_ = dt.strptime(df['depart_date_time'].iloc[i][:19], "%Y-%m-%dT%H:%M:%S").time()
    time.append(time_)

df['time'] = time
#df.head()

In [9]:
#creating variables dates, time and weekdays
from datetime import datetime

df['date']= pd.to_datetime(pd.Series(df['depart_date_time']).apply(str)).dt.date
df['date_weekday']= pd.to_datetime(pd.Series(df['depart_date_time']).apply(str)).dt.dayofweek

#df.head(3)

,id,depart_date_time,seats,prefs,notes,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,...,latitude_arr,longitude_arr,name_arr,id_dep,latitude_dep,longitude_dep,name_dep,time,date,date_weekday
0,7385002,2018-08-07T15:30:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Opsamling Rødovre station. Bilen er lille. Ikk...,0,269889,12.5,100,NaN,...,56.025167,9.896857,Smukfest,25834237,55.673514,12.465726,Rødovre,15:30:00,2018-08-07,1
1,7385006,2018-08-07T14:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,1399528,12.5,100,NaN,...,55.676097,12.568337,København,25829881,56.460584,10.036539,Randers,14:00:00,2018-08-07,1
2,7385007,2018-08-09T08:30:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Afgang fra Vesterbro Brandstation. Tidspunkt k...,0,1438456,12.5,100,NaN,...,55.844405,9.237394,Give,25829864,55.657333,12.538118,Enghavevej 168,08:30:00,2018-08-09,3

In [10]:
#limiting the dataset to Denmark (and a bit of Sweden and Germany), not necessary when we import DK data
#denmark_df = df[((df['latitude_dep'] > 54.564167) & (df['latitude_dep'] < 57.748611)) & ((df['longitude_dep'] > 8.075000) & (df['longitude_dep'] < 12.790278))] 
#denmark_df = denmark_df[((denmark_df['latitude_dep'] > 54.564167) & (denmark_df['latitude_dep'] < 57.748611)) & ((denmark_df['longitude_dep'] > 8.075000) & (denmark_df['longitude_dep'] < 12.790278)) & ((denmark_df['latitude_arr'] > 54.564167) & (denmark_df['latitude_arr'] < 57.748611)) & ((denmark_df['longitude_arr'] > 8.075000) & (denmark_df['longitude_arr'] < 12.790278))]

,id,depart_date_time,seats,prefs,notes,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,...,latitude_arr,longitude_arr,name_arr,id_dep,latitude_dep,longitude_dep,name_dep,time,date,date_weekday
0,7385002,2018-08-07T15:30:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Opsamling Rødovre station. Bilen er lille. Ikk...,0,269889,12.5,100,NaN,...,56.025167,9.896857,Smukfest,25834237,55.673514,12.465726,Rødovre,15:30:00,2018-08-07,1
1,7385006,2018-08-07T14:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,1399528,12.5,100,NaN,...,55.676097,12.568337,København,25829881,56.460584,10.036539,Randers,14:00:00,2018-08-07,1
2,7385007,2018-08-09T08:30:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Afgang fra Vesterbro Brandstation. Tidspunkt k...,0,1438456,12.5,100,NaN,...,55.844405,9.237394,Give,25829864,55.657333,12.538118,Enghavevej 168,08:30:00,2018-08-09,3
3,7385010,2018-08-07T06:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,56.959168,8.703492,Thisted,25829871,56.484930,8.589933,Struer,06:45:00,2018-08-07,1
4,7385011,2018-08-10T16:15:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,2318925,12.5,100,NaN,...,55.713441,9.528237,Nyboesgade,25829875,56.188259,10.184893,Olof Palmes Allé,16:15:00,2018-08-10,4
5,7385035,2018-08-06T20:30:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,734681,12.5,100,NaN,...,56.090674,9.766591,Ry,25830000,57.270904,9.945168,Brønderslev,20:30:00,2018-08-06,0
6,7385039,2018-08-06T19:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,2068395,12.5,100,NaN,...,56.199877,10.166024,Aarhus N,25830006,56.452027,9.396347,Viborg,19:45:00,2018-08-06,0
7,7385040,2018-08-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830008,55.042655,11.964033,Ørslev,09:15:00,2018-08-07,1
8,7385041,2018-08-08T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830010,55.042655,11.964033,Ørslev,09:15:00,2018-08-08,2
9,7385042,2018-08-09T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830012,55.042655,11.964033,Ørslev,09:15:00,2018-08-09,3
10,7385043,2018-08-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830014,55.042655,11.964033,Ørslev,09:15:00,2018-08-10,4
11,7385044,2018-08-13T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830016,55.042655,11.964033,Ørslev,09:15:00,2018-08-13,0
12,7385045,2018-08-14T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830018,55.042655,11.964033,Ørslev,09:15:00,2018-08-14,1
13,7385046,2018-08-15T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830020,55.042655,11.964033,Ørslev,09:15:00,2018-08-15,2
14,7385047,2018-08-16T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830022,55.042655,11.964033,Ørslev,09:15:00,2018-08-16,3
15,7385048,2018-08-17T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830024,55.042655,11.964033,Ørslev,09:15:00,2018-08-17,4
16,7385049,2018-08-20T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",26028492,55.042655,11.964033,Ørslev,09:15:00,2018-08-20,0
17,7385050,2018-08-21T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830028,55.042655,11.964033,Ørslev,09:15:00,2018-08-21,1
18,7385051,2018-08-22T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830030,55.042655,11.964033,Ørslev,09:15:00,2018-08-22,2
19,7385052,2018-08-23T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830032,55.042655,11.964033,Ørslev,09:15:00,2018-08-23,3
20,7385053,2018-08-24T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830034,55.042655,11.964033,Ørslev,09:15:00,2018-08-24,4
21,7385054,2018-09-03T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830036,55.042655,11.964033,Ørslev,09:15:00,2018-09-03,0
22,7385055,2018-09-04T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830038,55.042655,11.964033,Ørslev,09:15:00,2018-09-04,1
23,7385056,2018-09-05T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830040,55.042655,11.964033,Ørslev,09:15:00,2018-09-05,2
24,7385057,2018-09-06T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830042,55.042655,11.964033,Ørslev,09:15:00,2018-09-06,3
25,7385058,2018-09-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830044,55.042655,11.964033,Ørslev,09:15:00,2018-09-07,4
26,7385059,2018-09-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830046,55.042655,11.964033,Ørslev,09:15:00,2018-09-10,0
27,7385060,2018-09-11T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830048,55.042655,11.964033,Ørslev,09:15:00,2018-09-11,1
28,7385061,2018-09-12T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830050,55.042655,11.964033,Ørslev,09:15:00,2018-09-12,2
29,7385135,2018-08-07T18:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra tankstationen Ingo overfor Fisketorv...,3,2115457,12.5,100,NaN,...,55.042655,11.964033,Ørslev,25830217,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",18:00:00,2018-08-07,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13623,7365920,2018-08-09T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",2,2098291,12.5,100,NaN,...,56.155475,10.169179,"Silkeborgvej, Aarhus",25756369,56.138557,8.967322,Herning,16:00:00,2018-08-09,3
13624,7365921,2018-08-10T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",0,2098291,12.5,100,NaN,...,56.155475,10.169179,"Silkeborgvej, Aarhus",25762620,56.138557,8.967322,Herning,16:00:00,2018-08-10,4
13625,7365924,2018-08-07T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,0,2098291,12.5,100,NaN,...,56.138557,8.967322,Herning,25756515,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-07,1
13626,7365926,2018-08-09T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,55.138886,8.513871,Rømø,25816276,55.625293,12.455156,Avedøre St.,08:00:00,2018-08-09,3
13627,7365928,2018-08-11T11:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,55.625293,12.455156,Avedøre St.,25816286,55.138886,8.513871,Rømø,11:30:00,2018-08-11,5
13628,7365930,2018-08-08T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,56.138557,8.967322,Herning,25756513,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-08,2
13629,7365932,2018-08-09T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,2,2098291,12.5,100,NaN,...,56.138557,8.967322,Herning,25756434,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-09,3
13630,7365933,2018-08-05T10:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Turen går via Storbæltsbroen og varer ca. 5 ti...,0,119506,12.5,100,NaN,...,55.676097,12.568337,København,25756450,57.010218,9.886539,Aalborg SV,10:00:00,2018-08-05,6
13631,7365934,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",Jeg har mulighed for at samle op i hele Skibhu...,3,563375,12.5,100,NaN,...,55.509878,9.468172,Skovvangen 28,25756444,55.401174,10.387270,Odense Banegård Center,08:00:00,2018-08-03,4
13632,7365938,2018-08-10T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,56.138557,8.967322,Herning,25756460,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-10,4
13633,7365939,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...","Jeg kører fra Hansenberg (Skovvangen 28), og k...",3,563375,12.5,100,NaN,...,55.401174,10.387270,Odense Banegård Center,25780710,55.509878,9.468172,Skovvangen 28,15:30:00,2018-08-03,4
13634,7365950,2018-08-17T15:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Jeg kører fra Nørreport,0,280454,12.5,100,NaN,...,55.156415,8.768423,Skærbæk,25756531,55.676097,12.568337,København,15:15:00,2018-08-17,4
13635,7365952,2018-08-18T08:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,0,616336,12.5,100,NaN,...,55.651123,12.194711,Hedehusene,25940944,57.048819,9.921747,Aalborg,08:00:00,2018-08-18,5
13636,7365953,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,0,21405,12.5,100,NaN,...,55.467858,8.458275,"Esbjerg St., Jernbanegade, Esbjerg",25756537,55.672689,12.564869,"København H, Bernstorffsgade, København",15:30:00,2018-08-03,4
13637,7365956,2018-08-03T14:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,55.711311,9.536354,Vejle,25756694,57.462965,9.982867,Nørregade 31A,14:00:00,2018-08-03,4
13638,7365961,2018-08-05T20:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,57.462965,9.982867,Nørregade 31A,25756707,55.711311,9.536354,Vejle,20:00:00,2018-08-05,6
13639,7365962,2018-08-02T11:00:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1287620,12.5,100,NaN,...,56.150640,10.203812,Banegårdspladsen,25756586,56.460584,10.036539,Randers,11:00:00,2018-08-02,3
13640,7365964,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,2318353,12.5,100,NaN,...,56.194425,10.671048,Havnevej,25756656,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3
13641,7365965,2018-08-03T07:30:00+02:00,4,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,4,2318700,12.5,100,NaN,...,56.196327,10.677857,Ebeltoft,25756598,55.763516,12.494943,Kongens Lyngby,07:30:00,2018-08-03,4
13642,7365968,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,1,2318700,12.5,100,NaN,...,55.763516,12.494943,Kongens Lyngby,25756609,56.196327,10.677857,Ebeltoft,11:00:00,2018-08-03,4
13643,7365969,2018-08-12T17:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,0,1402216,12.5,100,NaN,...,55.676097,12.568337,Copenhagen,25756614,56.460584,10.036539,Randers,17:00:00,2018-08-12,6
13644,7365970,2018-08-04T17:15:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1691936,12.5,100,NaN,...,55.746153,9.147994,"Billund Airport - Terminal 1, Billund",25756618,57.043185,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",17:15:00,2018-08-04,5
13645,7365974,2018-08-03T15:30:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra P-pladsen ved Sygehuset, lige syd fo...",0,215247,12.5,100,NaN,...,55.971446,10.150336,"Odder St., Odder",25756753,55.639164,12.088802,"Roskilde St., Roskilde",15:30:00,2018-08-03,4
13646,7365985,2018-08-05T17:45:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra Saxsild Strand, opsamling efter afta...",1,215247,12.5,100,NaN,...,55.639164,12.088802,"Roskilde St., Roskilde",25756762,55.971446,10.150336,"Odder St., Odder",17:45:00,2018-08-05,6
13647,7365986,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,226175,12.5,100,NaN,...,48.856614,2.352222,"Paris, France",25756702,57.048819,9.921747,Aalborg,11:00:00,2018-08-03,4
13648,7365989,2018-08-04T07:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,1691936,12.5,100,NaN,...,57.043185,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",25756716,55.746153,9.147994,"Billund Airport - Terminal 1, Billund",07:30:00,2018-08-04,5
13649,7365991,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,1,2318353,12.5,100,NaN,...,56.194425,10.671048,Havnevej,25756720,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3
13650,7365996,2018-08-03T12:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,3,194876,12.5,100,NaN,...,56.425214,10.550971,"Djurs Sommerland, Randersvej, Nimtofte",25756743,56.171602,10.201916,Aarhus Universitet,12:00:00,2018-08-03,4
13651,7365997,2018-08-02T13:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,908968,12.5,100,NaN,...,57.043185,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",25756758,56.959168,8.703492,Thisted,13:30:00,2018-08-02,3
13652,7365999,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,56.959168,8.703492,Thisted,25756815,56.484930,8.589933,Struer,08:00:00,2018-08-03,4

In [11]:
#Make dummy variable of whether in Denmark or not
df['Denmark'] = (df['latitude_dep'] > 54.564167) & (df['latitude_dep'] < 57.748611) & (df['longitude_dep'] > 8.075000) & (df['longitude_dep'] < 12.790278).astype(int)
df

,id,depart_date_time,seats,prefs,notes,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,...,longitude_arr,name_arr,id_dep,latitude_dep,longitude_dep,name_dep,time,date,date_weekday,Denmark
0,7385002,2018-08-07T15:30:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Opsamling Rødovre station. Bilen er lille. Ikk...,0,269889,12.5,100,NaN,...,9.896857,Smukfest,25834237,55.673514,12.465726,Rødovre,15:30:00,2018-08-07,1,True
1,7385006,2018-08-07T14:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,1399528,12.5,100,NaN,...,12.568337,København,25829881,56.460584,10.036539,Randers,14:00:00,2018-08-07,1,True
2,7385007,2018-08-09T08:30:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Afgang fra Vesterbro Brandstation. Tidspunkt k...,0,1438456,12.5,100,NaN,...,9.237394,Give,25829864,55.657333,12.538118,Enghavevej 168,08:30:00,2018-08-09,3,True
3,7385010,2018-08-07T06:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,8.703492,Thisted,25829871,56.484930,8.589933,Struer,06:45:00,2018-08-07,1,True
4,7385011,2018-08-10T16:15:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,2318925,12.5,100,NaN,...,9.528237,Nyboesgade,25829875,56.188259,10.184893,Olof Palmes Allé,16:15:00,2018-08-10,4,True
5,7385035,2018-08-06T20:30:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,734681,12.5,100,NaN,...,9.766591,Ry,25830000,57.270904,9.945168,Brønderslev,20:30:00,2018-08-06,0,True
6,7385039,2018-08-06T19:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,2068395,12.5,100,NaN,...,10.166024,Aarhus N,25830006,56.452027,9.396347,Viborg,19:45:00,2018-08-06,0,True
7,7385040,2018-08-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830008,55.042655,11.964033,Ørslev,09:15:00,2018-08-07,1,True
8,7385041,2018-08-08T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830010,55.042655,11.964033,Ørslev,09:15:00,2018-08-08,2,True
9,7385042,2018-08-09T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830012,55.042655,11.964033,Ørslev,09:15:00,2018-08-09,3,True
10,7385043,2018-08-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830014,55.042655,11.964033,Ørslev,09:15:00,2018-08-10,4,True
11,7385044,2018-08-13T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830016,55.042655,11.964033,Ørslev,09:15:00,2018-08-13,0,True
12,7385045,2018-08-14T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830018,55.042655,11.964033,Ørslev,09:15:00,2018-08-14,1,True
13,7385046,2018-08-15T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830020,55.042655,11.964033,Ørslev,09:15:00,2018-08-15,2,True
14,7385047,2018-08-16T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830022,55.042655,11.964033,Ørslev,09:15:00,2018-08-16,3,True
15,7385048,2018-08-17T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830024,55.042655,11.964033,Ørslev,09:15:00,2018-08-17,4,True
16,7385049,2018-08-20T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",26028492,55.042655,11.964033,Ørslev,09:15:00,2018-08-20,0,True
17,7385050,2018-08-21T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830028,55.042655,11.964033,Ørslev,09:15:00,2018-08-21,1,True
18,7385051,2018-08-22T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830030,55.042655,11.964033,Ørslev,09:15:00,2018-08-22,2,True
19,7385052,2018-08-23T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830032,55.042655,11.964033,Ørslev,09:15:00,2018-08-23,3,True
20,7385053,2018-08-24T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830034,55.042655,11.964033,Ørslev,09:15:00,2018-08-24,4,True
21,7385054,2018-09-03T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830036,55.042655,11.964033,Ørslev,09:15:00,2018-09-03,0,True
22,7385055,2018-09-04T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830038,55.042655,11.964033,Ørslev,09:15:00,2018-09-04,1,True
23,7385056,2018-09-05T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830040,55.042655,11.964033,Ørslev,09:15:00,2018-09-05,2,True
24,7385057,2018-09-06T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830042,55.042655,11.964033,Ørslev,09:15:00,2018-09-06,3,True
25,7385058,2018-09-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830044,55.042655,11.964033,Ørslev,09:15:00,2018-09-07,4,True
26,7385059,2018-09-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830046,55.042655,11.964033,Ørslev,09:15:00,2018-09-10,0,True
27,7385060,2018-09-11T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830048,55.042655,11.964033,Ørslev,09:15:00,2018-09-11,1,True
28,7385061,2018-09-12T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830050,55.042655,11.964033,Ørslev,09:15:00,2018-09-12,2,True
29,7385135,2018-08-07T18:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra tankstationen Ingo overfor Fisketorv...,3,2115457,12.5,100,NaN,...,11.964033,Ørslev,25830217,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",18:00:00,2018-08-07,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13623,7365920,2018-08-09T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",2,2098291,12.5,100,NaN,...,10.169179,"Silkeborgvej, Aarhus",25756369,56.138557,8.967322,Herning,16:00:00,2018-08-09,3,True
13624,7365921,2018-08-10T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",0,2098291,12.5,100,NaN,...,10.169179,"Silkeborgvej, Aarhus",25762620,56.138557,8.967322,Herning,16:00:00,2018-08-10,4,True
13625,7365924,2018-08-07T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,0,2098291,12.5,100,NaN,...,8.967322,Herning,25756515,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-07,1,True
13626,7365926,2018-08-09T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,8.513871,Rømø,25816276,55.625293,12.455156,Avedøre St.,08:00:00,2018-08-09,3,True
13627,7365928,2018-08-11T11:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,12.455156,Avedøre St.,25816286,55.138886,8.513871,Rømø,11:30:00,2018-08-11,5,True
13628,7365930,2018-08-08T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,8.967322,Herning,25756513,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-08,2,True
13629,7365932,2018-08-09T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,2,2098291,12.5,100,NaN,...,8.967322,Herning,25756434,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-09,3,True
13630,7365933,2018-08-05T10:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Turen går via Storbæltsbroen og varer ca. 5 ti...,0,119506,12.5,100,NaN,...,12.568337,København,25756450,57.010218,9.886539,Aalborg SV,10:00:00,2018-08-05,6,True
13631,7365934,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",Jeg har mulighed for at samle op i hele Skibhu...,3,563375,12.5,100,NaN,...,9.468172,Skovvangen 28,25756444,55.401174,10.387270,Odense Banegård Center,08:00:00,2018-08-03,4,True
13632,7365938,2018-08-10T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,8.967322,Herning,25756460,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-10,4,True
13633,7365939,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...","Jeg kører fra Hansenberg (Skovvangen 28), og k...",3,563375,12.5,100,NaN,...,10.387270,Odense Banegård Center,25780710,55.509878,9.468172,Skovvangen 28,15:30:00,2018-08-03,4,True
13634,7365950,2018-08-17T15:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Jeg kører fra Nørreport,0,280454,12.5,100,NaN,...,8.768423,Skærbæk,25756531,55.676097,12.568337,København,15:15:00,2018-08-17,4,True
13635,7365952,2018-08-18T08:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,0,616336,12.5,100,NaN,...,12.194711,Hedehusene,25940944,57.048819,9.921747,Aalborg,08:00:00,2018-08-18,5,True
13636,7365953,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,0,21405,12.5,100,NaN,...,8.458275,"Esbjerg St., Jernbanegade, Esbjerg",25756537,55.672689,12.564869,"København H, Bernstorffsgade, København",15:30:00,2018-08-03,4,True
13637,7365956,2018-08-03T14:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,9.536354,Vejle,25756694,57.462965,9.982867,Nørregade 31A,14:00:00,2018-08-03,4,True
13638,7365961,2018-08-05T20:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,9.982867,Nørregade 31A,25756707,55.711311,9.536354,Vejle,20:00:00,2018-08-05,6,True
13639,7365962,2018-08-02T11:00:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1287620,12.5,100,NaN,...,10.203812,Banegårdspladsen,25756586,56.460584,10.036539,Randers,11:00:00,2018-08-02,3,True
13640,7365964,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,2318353,12.5,100,NaN,...,10.671048,Havnevej,25756656,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3,True
13641,7365965,2018-08-03T07:30:00+02:00,4,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,4,2318700,12.5,100,NaN,...,10.677857,Ebeltoft,25756598,55.763516,12.494943,Kongens Lyngby,07:30:00,2018-08-03,4,True
13642,7365968,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,1,2318700,12.5,100,NaN,...,12.494943,Kongens Lyngby,25756609,56.196327,10.677857,Ebeltoft,11:00:00,2018-08-03,4,True
13643,7365969,2018-08-12T17:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,0,1402216,12.5,100,NaN,...,12.568337,Copenhagen,25756614,56.460584,10.036539,Randers,17:00:00,2018-08-12,6,True
13644,7365970,2018-08-04T17:15:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1691936,12.5,100,NaN,...,9.147994,"Billund Airport - Terminal 1, Billund",25756618,57.043185,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",17:15:00,2018-08-04,5,True
13645,7365974,2018-08-03T15:30:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra P-pladsen ved Sygehuset, lige syd fo...",0,215247,12.5,100,NaN,...,10.150336,"Odder St., Odder",25756753,55.639164,12.088802,"Roskilde St., Roskilde",15:30:00,2018-08-03,4,True
13646,7365985,2018-08-05T17:45:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra Saxsild Strand, opsamling efter afta...",1,215247,12.5,100,NaN,...,12.088802,"Roskilde St., Roskilde",25756762,55.971446,10.150336,"Odder St., Odder",17:45:00,2018-08-05,6,True
13647,7365986,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,226175,12.5,100,NaN,...,2.352222,"Paris, France",25756702,57.048819,9.921747,Aalborg,11:00:00,2018-08-03,4,True
13648,7365989,2018-08-04T07:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,1691936,12.5,100,NaN,...,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",25756716,55.746153,9.147994,"Billund Airport - Terminal 1, Billund",07:30:00,2018-08-04,5,True
13649,7365991,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,1,2318353,12.5,100,NaN,...,10.671048,Havnevej,25756720,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3,True
13650,7365996,2018-08-03T12:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,3,194876,12.5,100,NaN,...,10.550971,"Djurs Sommerland, Randersvej, Nimtofte",25756743,56.171602,10.201916,Aarhus Universitet,12:00:00,2018-08-03,4,True
13651,7365997,2018-08-02T13:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,908968,12.5,100,NaN,...,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",25756758,56.959168,8.703492,Thisted,13:30:00,2018-08-02,3,True
13652,7365999,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,8.703492,Thisted,25756815,56.484930,8.589933,Struer,08:00:00,2018-08-03,4,True

In [12]:
#Make dummy variable of whether at Sjælland depature or not
df['SJ_dep'] = (df['latitude_dep'] > 54.564167) & (df['latitude_dep'] < 57.748611) & (df['longitude_dep'] > 10.958935) & (df['longitude_dep'] < 12.790278).astype(int)
df

,id,depart_date_time,seats,prefs,notes,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,...,name_arr,id_dep,latitude_dep,longitude_dep,name_dep,time,date,date_weekday,Denmark,SJ_dep
0,7385002,2018-08-07T15:30:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Opsamling Rødovre station. Bilen er lille. Ikk...,0,269889,12.5,100,NaN,...,Smukfest,25834237,55.673514,12.465726,Rødovre,15:30:00,2018-08-07,1,True,True
1,7385006,2018-08-07T14:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,1399528,12.5,100,NaN,...,København,25829881,56.460584,10.036539,Randers,14:00:00,2018-08-07,1,True,False
2,7385007,2018-08-09T08:30:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Afgang fra Vesterbro Brandstation. Tidspunkt k...,0,1438456,12.5,100,NaN,...,Give,25829864,55.657333,12.538118,Enghavevej 168,08:30:00,2018-08-09,3,True,True
3,7385010,2018-08-07T06:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,Thisted,25829871,56.484930,8.589933,Struer,06:45:00,2018-08-07,1,True,False
4,7385011,2018-08-10T16:15:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,2318925,12.5,100,NaN,...,Nyboesgade,25829875,56.188259,10.184893,Olof Palmes Allé,16:15:00,2018-08-10,4,True,False
5,7385035,2018-08-06T20:30:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,734681,12.5,100,NaN,...,Ry,25830000,57.270904,9.945168,Brønderslev,20:30:00,2018-08-06,0,True,False
6,7385039,2018-08-06T19:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,2068395,12.5,100,NaN,...,Aarhus N,25830006,56.452027,9.396347,Viborg,19:45:00,2018-08-06,0,True,False
7,7385040,2018-08-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830008,55.042655,11.964033,Ørslev,09:15:00,2018-08-07,1,True,True
8,7385041,2018-08-08T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830010,55.042655,11.964033,Ørslev,09:15:00,2018-08-08,2,True,True
9,7385042,2018-08-09T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830012,55.042655,11.964033,Ørslev,09:15:00,2018-08-09,3,True,True
10,7385043,2018-08-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830014,55.042655,11.964033,Ørslev,09:15:00,2018-08-10,4,True,True
11,7385044,2018-08-13T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830016,55.042655,11.964033,Ørslev,09:15:00,2018-08-13,0,True,True
12,7385045,2018-08-14T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830018,55.042655,11.964033,Ørslev,09:15:00,2018-08-14,1,True,True
13,7385046,2018-08-15T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830020,55.042655,11.964033,Ørslev,09:15:00,2018-08-15,2,True,True
14,7385047,2018-08-16T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830022,55.042655,11.964033,Ørslev,09:15:00,2018-08-16,3,True,True
15,7385048,2018-08-17T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830024,55.042655,11.964033,Ørslev,09:15:00,2018-08-17,4,True,True
16,7385049,2018-08-20T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",26028492,55.042655,11.964033,Ørslev,09:15:00,2018-08-20,0,True,True
17,7385050,2018-08-21T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830028,55.042655,11.964033,Ørslev,09:15:00,2018-08-21,1,True,True
18,7385051,2018-08-22T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830030,55.042655,11.964033,Ørslev,09:15:00,2018-08-22,2,True,True
19,7385052,2018-08-23T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830032,55.042655,11.964033,Ørslev,09:15:00,2018-08-23,3,True,True
20,7385053,2018-08-24T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830034,55.042655,11.964033,Ørslev,09:15:00,2018-08-24,4,True,True
21,7385054,2018-09-03T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830036,55.042655,11.964033,Ørslev,09:15:00,2018-09-03,0,True,True
22,7385055,2018-09-04T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830038,55.042655,11.964033,Ørslev,09:15:00,2018-09-04,1,True,True
23,7385056,2018-09-05T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830040,55.042655,11.964033,Ørslev,09:15:00,2018-09-05,2,True,True
24,7385057,2018-09-06T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830042,55.042655,11.964033,Ørslev,09:15:00,2018-09-06,3,True,True
25,7385058,2018-09-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830044,55.042655,11.964033,Ørslev,09:15:00,2018-09-07,4,True,True
26,7385059,2018-09-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830046,55.042655,11.964033,Ørslev,09:15:00,2018-09-10,0,True,True
27,7385060,2018-09-11T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830048,55.042655,11.964033,Ørslev,09:15:00,2018-09-11,1,True,True
28,7385061,2018-09-12T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",25830050,55.042655,11.964033,Ørslev,09:15:00,2018-09-12,2,True,True
29,7385135,2018-08-07T18:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra tankstationen Ingo overfor Fisketorv...,3,2115457,12.5,100,NaN,...,Ørslev,25830217,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",18:00:00,2018-08-07,1,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13623,7365920,2018-08-09T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",2,2098291,12.5,100,NaN,...,"Silkeborgvej, Aarhus",25756369,56.138557,8.967322,Herning,16:00:00,2018-08-09,3,True,False
13624,7365921,2018-08-10T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",0,2098291,12.5,100,NaN,...,"Silkeborgvej, Aarhus",25762620,56.138557,8.967322,Herning,16:00:00,2018-08-10,4,True,False
13625,7365924,2018-08-07T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,0,2098291,12.5,100,NaN,...,Herning,25756515,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-07,1,True,False
13626,7365926,2018-08-09T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,Rømø,25816276,55.625293,12.455156,Avedøre St.,08:00:00,2018-08-09,3,True,True
13627,7365928,2018-08-11T11:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,Avedøre St.,25816286,55.138886,8.513871,Rømø,11:30:00,2018-08-11,5,True,False
13628,7365930,2018-08-08T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,Herning,25756513,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-08,2,True,False
13629,7365932,2018-08-09T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,2,2098291,12.5,100,NaN,...,Herning,25756434,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-09,3,True,False
13630,7365933,2018-08-05T10:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Turen går via Storbæltsbroen og varer ca. 5 ti...,0,119506,12.5,100,NaN,...,København,25756450,57.010218,9.886539,Aalborg SV,10:00:00,2018-08-05,6,True,False
13631,7365934,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",Jeg har mulighed for at samle op i hele Skibhu...,3,563375,12.5,100,NaN,...,Skovvangen 28,25756444,55.401174,10.387270,Odense Banegård Center,08:00:00,2018-08-03,4,True,False
13632,7365938,2018-08-10T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,Herning,25756460,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-10,4,True,False
13633,7365939,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...","Jeg kører fra Hansenberg (Skovvangen 28), og k...",3,563375,12.5,100,NaN,...,Odense Banegård Center,25780710,55.509878,9.468172,Skovvangen 28,15:30:00,2018-08-03,4,True,False
13634,7365950,2018-08-17T15:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Jeg kører fra Nørreport,0,280454,12.5,100,NaN,...,Skærbæk,25756531,55.676097,12.568337,København,15:15:00,2018-08-17,4,True,True
13635,7365952,2018-08-18T08:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,0,616336,12.5,100,NaN,...,Hedehusene,25940944,57.048819,9.921747,Aalborg,08:00:00,2018-08-18,5,True,False
13636,7365953,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,0,21405,12.5,100,NaN,...,"Esbjerg St., Jernbanegade, Esbjerg",25756537,55.672689,12.564869,"København H, Bernstorffsgade, København",15:30:00,2018-08-03,4,True,True
13637,7365956,2018-08-03T14:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,Vejle,25756694,57.462965,9.982867,Nørregade 31A,14:00:00,2018-08-03,4,True,False
13638,7365961,2018-08-05T20:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,Nørregade 31A,25756707,55.711311,9.536354,Vejle,20:00:00,2018-08-05,6,True,False
13639,7365962,2018-08-02T11:00:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1287620,12.5,100,NaN,...,Banegårdspladsen,25756586,56.460584,10.036539,Randers,11:00:00,2018-08-02,3,True,False
13640,7365964,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,2318353,12.5,100,NaN,...,Havnevej,25756656,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3,True,True
13641,7365965,2018-08-03T07:30:00+02:00,4,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,4,2318700,12.5,100,NaN,...,Ebeltoft,25756598,55.763516,12.494943,Kongens Lyngby,07:30:00,2018-08-03,4,True,True
13642,7365968,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,1,2318700,12.5,100,NaN,...,Kongens Lyngby,25756609,56.196327,10.677857,Ebeltoft,11:00:00,2018-08-03,4,True,False
13643,7365969,2018-08-12T17:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,0,1402216,12.5,100,NaN,...,Copenhagen,25756614,56.460584,10.036539,Randers,17:00:00,2018-08-12,6,True,False
13644,7365970,2018-08-04T17:15:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1691936,12.5,100,NaN,...,"Billund Airport - Terminal 1, Billund",25756618,57.043185,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",17:15:00,2018-08-04,5,True,False
13645,7365974,2018-08-03T15:30:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra P-pladsen ved Sygehuset, lige syd fo...",0,215247,12.5,100,NaN,...,"Odder St., Odder",25756753,55.639164,12.088802,"Roskilde St., Roskilde",15:30:00,2018-08-03,4,True,True
13646,7365985,2018-08-05T17:45:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra Saxsild Strand, opsamling efter afta...",1,215247,12.5,100,NaN,...,"Roskilde St., Roskilde",25756762,55.971446,10.150336,"Odder St., Odder",17:45:00,2018-08-05,6,True,False
13647,7365986,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,226175,12.5,100,NaN,...,"Paris, France",25756702,57.048819,9.921747,Aalborg,11:00:00,2018-08-03,4,True,False
13648,7365989,2018-08-04T07:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,1691936,12.5,100,NaN,...,"Aalborg St., John F. Kennedys Plads, Aalborg",25756716,55.746153,9.147994,"Billund Airport - Terminal 1, Billund",07:30:00,2018-08-04,5,True,False
13649,7365991,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,1,2318353,12.5,100,NaN,...,Havnevej,25756720,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3,True,True
13650,7365996,2018-08-03T12:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,3,194876,12.5,100,NaN,...,"Djurs Sommerland, Randersvej, Nimtofte",25756743,56.171602,10.201916,Aarhus Universitet,12:00:00,2018-08-03,4,True,False
13651,7365997,2018-08-02T13:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,908968,12.5,100,NaN,...,"Aalborg St., John F. Kennedys Plads, Aalborg",25756758,56.959168,8.703492,Thisted,13:30:00,2018-08-02,3,True,False
13652,7365999,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,Thisted,25756815,56.484930,8.589933,Struer,08:00:00,2018-08-03,4,True,False

In [13]:
#Make dummy variable of whether at Sjælland arrival or not
df['SJ_arr'] = (df['latitude_arr'] > 54.564167) & (df['latitude_arr'] < 57.748611) & (df['longitude_arr'] > 10.958935) & (df['longitude_arr'] < 12.790278).astype(int)
df

,id,depart_date_time,seats,prefs,notes,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,...,id_dep,latitude_dep,longitude_dep,name_dep,time,date,date_weekday,Denmark,SJ_dep,SJ_arr
0,7385002,2018-08-07T15:30:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Opsamling Rødovre station. Bilen er lille. Ikk...,0,269889,12.5,100,NaN,...,25834237,55.673514,12.465726,Rødovre,15:30:00,2018-08-07,1,True,True,False
1,7385006,2018-08-07T14:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,1399528,12.5,100,NaN,...,25829881,56.460584,10.036539,Randers,14:00:00,2018-08-07,1,True,False,True
2,7385007,2018-08-09T08:30:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Afgang fra Vesterbro Brandstation. Tidspunkt k...,0,1438456,12.5,100,NaN,...,25829864,55.657333,12.538118,Enghavevej 168,08:30:00,2018-08-09,3,True,True,False
3,7385010,2018-08-07T06:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,25829871,56.484930,8.589933,Struer,06:45:00,2018-08-07,1,True,False,False
4,7385011,2018-08-10T16:15:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,2318925,12.5,100,NaN,...,25829875,56.188259,10.184893,Olof Palmes Allé,16:15:00,2018-08-10,4,True,False,False
5,7385035,2018-08-06T20:30:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,734681,12.5,100,NaN,...,25830000,57.270904,9.945168,Brønderslev,20:30:00,2018-08-06,0,True,False,False
6,7385039,2018-08-06T19:45:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,2068395,12.5,100,NaN,...,25830006,56.452027,9.396347,Viborg,19:45:00,2018-08-06,0,True,False,False
7,7385040,2018-08-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830008,55.042655,11.964033,Ørslev,09:15:00,2018-08-07,1,True,True,True
8,7385041,2018-08-08T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830010,55.042655,11.964033,Ørslev,09:15:00,2018-08-08,2,True,True,True
9,7385042,2018-08-09T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830012,55.042655,11.964033,Ørslev,09:15:00,2018-08-09,3,True,True,True
10,7385043,2018-08-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830014,55.042655,11.964033,Ørslev,09:15:00,2018-08-10,4,True,True,True
11,7385044,2018-08-13T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830016,55.042655,11.964033,Ørslev,09:15:00,2018-08-13,0,True,True,True
12,7385045,2018-08-14T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830018,55.042655,11.964033,Ørslev,09:15:00,2018-08-14,1,True,True,True
13,7385046,2018-08-15T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830020,55.042655,11.964033,Ørslev,09:15:00,2018-08-15,2,True,True,True
14,7385047,2018-08-16T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830022,55.042655,11.964033,Ørslev,09:15:00,2018-08-16,3,True,True,True
15,7385048,2018-08-17T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830024,55.042655,11.964033,Ørslev,09:15:00,2018-08-17,4,True,True,True
16,7385049,2018-08-20T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,26028492,55.042655,11.964033,Ørslev,09:15:00,2018-08-20,0,True,True,True
17,7385050,2018-08-21T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830028,55.042655,11.964033,Ørslev,09:15:00,2018-08-21,1,True,True,True
18,7385051,2018-08-22T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830030,55.042655,11.964033,Ørslev,09:15:00,2018-08-22,2,True,True,True
19,7385052,2018-08-23T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830032,55.042655,11.964033,Ørslev,09:15:00,2018-08-23,3,True,True,True
20,7385053,2018-08-24T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830034,55.042655,11.964033,Ørslev,09:15:00,2018-08-24,4,True,True,True
21,7385054,2018-09-03T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830036,55.042655,11.964033,Ørslev,09:15:00,2018-09-03,0,True,True,True
22,7385055,2018-09-04T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830038,55.042655,11.964033,Ørslev,09:15:00,2018-09-04,1,True,True,True
23,7385056,2018-09-05T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830040,55.042655,11.964033,Ørslev,09:15:00,2018-09-05,2,True,True,True
24,7385057,2018-09-06T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830042,55.042655,11.964033,Ørslev,09:15:00,2018-09-06,3,True,True,True
25,7385058,2018-09-07T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830044,55.042655,11.964033,Ørslev,09:15:00,2018-09-07,4,True,True,True
26,7385059,2018-09-10T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830046,55.042655,11.964033,Ørslev,09:15:00,2018-09-10,0,True,True,True
27,7385060,2018-09-11T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830048,55.042655,11.964033,Ørslev,09:15:00,2018-09-11,1,True,True,True
28,7385061,2018-09-12T09:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,...,25830050,55.042655,11.964033,Ørslev,09:15:00,2018-09-12,2,True,True,True
29,7385135,2018-08-07T18:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Køres fra tankstationen Ingo overfor Fisketorv...,3,2115457,12.5,100,NaN,...,25830217,55.663134,12.560550,"Fisketorvet, Dybbølsbro (Kalvebod Brygge)",18:00:00,2018-08-07,1,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13623,7365920,2018-08-09T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",2,2098291,12.5,100,NaN,...,25756369,56.138557,8.967322,Herning,16:00:00,2018-08-09,3,True,False,False
13624,7365921,2018-08-10T16:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Jeg kan samle op det meste af Herning, og kan ...",0,2098291,12.5,100,NaN,...,25762620,56.138557,8.967322,Herning,16:00:00,2018-08-10,4,True,False,False
13625,7365924,2018-08-07T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,0,2098291,12.5,100,NaN,...,25756515,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-07,1,True,False,False
13626,7365926,2018-08-09T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,25816276,55.625293,12.455156,Avedøre St.,08:00:00,2018-08-09,3,True,True,False
13627,7365928,2018-08-11T11:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,280454,12.5,100,NaN,...,25816286,55.138886,8.513871,Rømø,11:30:00,2018-08-11,5,True,False,True
13628,7365930,2018-08-08T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,25756513,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-08,2,True,False,False
13629,7365932,2018-08-09T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,2,2098291,12.5,100,NaN,...,25756434,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-09,3,True,False,False
13630,7365933,2018-08-05T10:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Turen går via Storbæltsbroen og varer ca. 5 ti...,0,119506,12.5,100,NaN,...,25756450,57.010218,9.886539,Aalborg SV,10:00:00,2018-08-05,6,True,False,True
13631,7365934,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",Jeg har mulighed for at samle op i hele Skibhu...,3,563375,12.5,100,NaN,...,25756444,55.401174,10.387270,Odense Banegård Center,08:00:00,2018-08-03,4,True,False,False
13632,7365938,2018-08-10T07:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",Jeg samler som udgangspunkt op ved jysk (finde...,1,2098291,12.5,100,NaN,...,25756460,56.155475,10.169179,Silkeborgvej,07:00:00,2018-08-10,4,True,False,False
13633,7365939,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...","Jeg kører fra Hansenberg (Skovvangen 28), og k...",3,563375,12.5,100,NaN,...,25780710,55.509878,9.468172,Skovvangen 28,15:30:00,2018-08-03,4,True,False,False
13634,7365950,2018-08-17T15:15:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",Jeg kører fra Nørreport,0,280454,12.5,100,NaN,...,25756531,55.676097,12.568337,København,15:15:00,2018-08-17,4,True,True,False
13635,7365952,2018-08-18T08:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,0,616336,12.5,100,NaN,...,25940944,57.048819,9.921747,Aalborg,08:00:00,2018-08-18,5,True,False,True
13636,7365953,2018-08-03T15:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,0,21405,12.5,100,NaN,...,25756537,55.672689,12.564869,"København H, Bernstorffsgade, København",15:30:00,2018-08-03,4,True,True,False
13637,7365956,2018-08-03T14:00:00+02:00,2,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,25756694,57.462965,9.982867,Nørregade 31A,14:00:00,2018-08-03,4,True,False,False
13638,7365961,2018-08-05T20:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Sætter af og samler gerne op i Aalborg, men ku...",1,108687,12.5,100,NaN,...,25756707,55.711311,9.536354,Vejle,20:00:00,2018-08-05,6,True,False,False
13639,7365962,2018-08-02T11:00:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1287620,12.5,100,NaN,...,25756586,56.460584,10.036539,Randers,11:00:00,2018-08-02,3,True,False,False
13640,7365964,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,2318353,12.5,100,NaN,...,25756656,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3,True,True,False
13641,7365965,2018-08-03T07:30:00+02:00,4,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,4,2318700,12.5,100,NaN,...,25756598,55.763516,12.494943,Kongens Lyngby,07:30:00,2018-08-03,4,True,True,False
13642,7365968,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,1,2318700,12.5,100,NaN,...,25756609,56.196327,10.677857,Ebeltoft,11:00:00,2018-08-03,4,True,False,True
13643,7365969,2018-08-12T17:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,0,1402216,12.5,100,NaN,...,25756614,56.460584,10.036539,Randers,17:00:00,2018-08-12,6,True,False,True
13644,7365970,2018-08-04T17:15:00+02:00,2,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,2,1691936,12.5,100,NaN,...,25756618,57.043185,9.917151,"Aalborg St., John F. Kennedys Plads, Aalborg",17:15:00,2018-08-04,5,True,False,False
13645,7365974,2018-08-03T15:30:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra P-pladsen ved Sygehuset, lige syd fo...",0,215247,12.5,100,NaN,...,25756753,55.639164,12.088802,"Roskilde St., Roskilde",15:30:00,2018-08-03,4,True,True,False
13646,7365985,2018-08-05T17:45:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...","Kører fra Saxsild Strand, opsamling efter afta...",1,215247,12.5,100,NaN,...,25756762,55.971446,10.150336,"Odder St., Odder",17:45:00,2018-08-05,6,True,False,True
13647,7365986,2018-08-03T11:00:00+02:00,1,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,1,226175,12.5,100,NaN,...,25756702,57.048819,9.921747,Aalborg,11:00:00,2018-08-03,4,True,False,False
13648,7365989,2018-08-04T07:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,3,1691936,12.5,100,NaN,...,25756716,55.746153,9.147994,"Billund Airport - Terminal 1, Billund",07:30:00,2018-08-04,5,True,False,False
13649,7365991,2018-08-02T11:45:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '1', 'anim...",NaN,1,2318353,12.5,100,NaN,...,25756720,55.702552,12.533707,Frederiksborgvej 12,11:45:00,2018-08-02,3,True,True,False
13650,7365996,2018-08-03T12:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '0', 'anim...",NaN,3,194876,12.5,100,NaN,...,25756743,56.171602,10.201916,Aarhus Universitet,12:00:00,2018-08-03,4,True,False,False
13651,7365997,2018-08-02T13:30:00+02:00,3,"{'chat': '0', 'kids': '0', 'music': '0', 'anim...",NaN,3,908968,12.5,100,NaN,...,25756758,56.959168,8.703492,Thisted,13:30:00,2018-08-02,3,True,False,False
13652,7365999,2018-08-03T08:00:00+02:00,3,"{'chat': '0', 'kids': '1', 'music': '1', 'anim...",NaN,3,906186,12.5,100,NaN,...,25756815,56.484930,8.589933,Struer,08:00:00,2018-08-03,4,True,False,False

In [53]:
#lav dummyvariabel for om der er tale om krydsning af storebælt eller ej
df['betalingsvej'] = (df['SJ_dep'])*1 + (df['SJ_arr'])*1

betalingsvej_dummy= []
for i in range(0, len(df)):
    if (df['betalingsvej'][i]) == 1:
        betalingsvej_dummy.append(1)
    else :
        betalingsvej_dummy.append(0)

df['betalingsvej_dummy'] = betalingsvej_dummy
df.head(0)

,id,depart_date_time,seats,notes,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,accept_cash,...,longitude_dep,name_dep,time,date,date_weekday,Denmark,SJ_dep,SJ_arr,betalingsvej,betalingsvej_dummy
0,7385002,2018-08-07T15:30:00+02:00,2,Opsamling Rødovre station. Bilen er lille. Ikk...,0,269889,12.5,100,NaN,False,...,12.465726,Rødovre,15:30:00,2018-08-07,1,True,True,False,1,1
1,7385006,2018-08-07T14:00:00+02:00,3,NaN,3,1399528,12.5,100,NaN,False,...,10.036539,Randers,14:00:00,2018-08-07,1,True,False,True,1,1
2,7385007,2018-08-09T08:30:00+02:00,1,Afgang fra Vesterbro Brandstation. Tidspunkt k...,0,1438456,12.5,100,NaN,False,...,12.538118,Enghavevej 168,08:30:00,2018-08-09,3,True,True,False,1,1
3,7385010,2018-08-07T06:45:00+02:00,3,NaN,3,906186,12.5,100,NaN,False,...,8.589933,Struer,06:45:00,2018-08-07,1,True,False,False,0,0
4,7385011,2018-08-10T16:15:00+02:00,2,NaN,1,2318925,12.5,100,NaN,False,...,10.184893,Olof Palmes Allé,16:15:00,2018-08-10,4,True,False,False,0,0
5,7385035,2018-08-06T20:30:00+02:00,3,NaN,3,734681,12.5,100,NaN,False,...,9.945168,Brønderslev,20:30:00,2018-08-06,0,True,False,False,0,0
6,7385039,2018-08-06T19:45:00+02:00,3,NaN,3,2068395,12.5,100,NaN,False,...,9.396347,Viborg,19:45:00,2018-08-06,0,True,False,False,0,0
7,7385040,2018-08-07T09:15:00+02:00,3,Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,False,...,11.964033,Ørslev,09:15:00,2018-08-07,1,True,True,True,2,0
8,7385041,2018-08-08T09:15:00+02:00,3,Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,False,...,11.964033,Ørslev,09:15:00,2018-08-08,2,True,True,True,2,0
9,7385042,2018-08-09T09:15:00+02:00,3,Køres fra Shell i Ørslev på Københavnsvej. Ing...,3,2115457,12.5,100,NaN,False,...,11.964033,Ørslev,09:15:00,2018-08-09,3,True,True,True,2,0

In [56]:
df.keys()
#Delete - 'prefs', 'notes', 'overview_polyline', 'waypoints_attritubes'
df_drop = df.drop(['notes', 'overview_polyline', 'waypoints_attributes'], 1)
df_drop.head()

,id,depart_date_time,seats,free_seats,user_id,handle_fee_rate,handle_fee_ceiling_factor,handle_fee_maximum,accept_cash,accept_online_payment,...,longitude_dep,name_dep,time,date,date_weekday,Denmark,SJ_dep,SJ_arr,betalingsvej,betalingsvej_dummy
0,7385002,2018-08-07T15:30:00+02:00,2,0,269889,12.5,100,NaN,False,True,...,12.465726,Rødovre,15:30:00,2018-08-07,1,True,True,False,1,1
1,7385006,2018-08-07T14:00:00+02:00,3,3,1399528,12.5,100,NaN,False,True,...,10.036539,Randers,14:00:00,2018-08-07,1,True,False,True,1,1
2,7385007,2018-08-09T08:30:00+02:00,1,0,1438456,12.5,100,NaN,False,True,...,12.538118,Enghavevej 168,08:30:00,2018-08-09,3,True,True,False,1,1
3,7385010,2018-08-07T06:45:00+02:00,3,3,906186,12.5,100,NaN,False,True,...,8.589933,Struer,06:45:00,2018-08-07,1,True,False,False,0,0
4,7385011,2018-08-10T16:15:00+02:00,2,1,2318925,12.5,100,NaN,False,True,...,10.184893,Olof Palmes Allé,16:15:00,2018-08-10,4,True,False,False,0,0

In [60]:
#Without duplicates
df_drop_ = df_drop[df_drop.duplicated(['id'], keep=False)]
#If this length = 0 we have 0 duplicates on the id variable
len(df_drop_)

0

In [62]:
#Import the dataframe:
df = pd.read_csv('GoMore_Data_DK_variables.csv', sep=',', low_memory=False)
print('This dataset consists of ' + str(len(df_test)) + ' observations')

This dataset consists of 13653 observations

In [ ]:
#Add code to new variables here:

In [ ]:
#Save the file, and delete the old file in Github before uploading this one (same name)
df_drop.to_csv('GoMore_Data_DK_variables.csv', index=False)